### ISSUE TITLE
/etc/hosts keeps changing after reboot

### ISSUE THREAD

**Issue by alex-leonhardt** [number5/cloud-init#5]
Hi,

we're managing VMs that are initialized via cloud-init and noticed that after each reboot, the /etc/hosts is back to its "templated version" rather than what the config management system had updated it to.

I suppose that this line https://github.com/number5/cloud-init/blob/master/cloudinit/config/cc_update_etc_hosts.py#L24 is why it does that - is there any objection to changing this to PER_ONCE instead of PER_ALWAYS ?

If so, is there a plan to make this configurable via cloud.cfg ? OR - am I on the wrong track here :) ? 

Thanks!
Alex

**Comment by number5** [comment]
Hi Alex,

This is only a code mirror, please report your bug to https://bugs.launchpad.net/cloud-init

Thanks!

**Comment by alex-leonhardt** [comment]
Oh! Heh, thanks! :)
